-- =========================================================
-- Problem 1: Total revenue generated by the business
-- Business Use: Understand overall business performance
-- =========================================================
SELECT SUM(amount) AS total_revenue
FROM payment;



-- =========================================================
-- Problem 2: Total number of rentals
-- Business Use: Measure customer demand and engagement
-- =========================================================
SELECT COUNT(*) AS total_rentals
FROM rental;


-- =========================================================
-- Problem 3: Daily revenue trend
-- Business Use: Identify peak and low-performing days
-- =========================================================
SELECT DATE(payment_date) AS date, SUM(amount) AS revenue
FROM payment
GROUP BY DATE(payment_date)
ORDER BY date;


-- =========================================================
-- Problem 4: Monthly revenue trend
-- Business Use: Detect seasonality in rentals
-- =========================================================
SELECT DATE_FORMAT(payment_date,'%Y-%m') AS month,
       SUM(amount) AS revenue
FROM payment
GROUP BY month
ORDER BY month;

-- =========================================================
-- Problem 5: Top 10 highest rented movies
-- Business Use: Focus marketing on best-performing films
-- =========================================================
SELECT f.title, COUNT(r.rental_id) AS total_rentals
FROM film f
JOIN inventory i ON f.film_id = i.film_id
JOIN rental r ON i.inventory_id = r.inventory_id
GROUP BY f.title
ORDER BY total_rentals DESC
LIMIT 10;

-- =========================================================
-- Problem 6: Least rented movies
-- Business Use: Identify low-demand content
-- =========================================================
SELECT f.title, COUNT(r.rental_id) AS rentals
FROM film f
LEFT JOIN inventory i ON f.film_id = i.film_id
LEFT JOIN rental r ON i.inventory_id = r.inventory_id
GROUP BY f.title
ORDER BY rentals ASC
LIMIT 10;

-- =========================================================
-- Problem 7: Revenue by movie category
-- Business Use: Decide which genre to invest more in
-- =========================================================
SELECT c.name AS category, SUM(p.amount) AS revenue
FROM category c
JOIN film_category fc ON c.category_id = fc.category_id
JOIN film f ON fc.film_id = f.film_id
JOIN inventory i ON f.film_id = i.film_id
JOIN rental r ON i.inventory_id = r.inventory_id
JOIN payment p ON r.rental_id = p.rental_id
GROUP BY c.name
ORDER BY revenue DESC;


-- =========================================================
-- Problem 8: Average rental duration per movie
-- Business Use: Understand customer watching behavior
-- =========================================================
SELECT f.title,
       AVG(DATEDIFF(r.return_date, r.rental_date)) AS avg_days
FROM film f
JOIN inventory i ON f.film_id = i.film_id
JOIN rental r ON i.inventory_id = r.inventory_id
GROUP BY f.title;

-- =========================================================
-- Problem 9: Top 10 highest paying customers (CLV)
-- Business Use: Identify high-value customers
-- =========================================================
SELECT c.customer_id,
       CONCAT(c.first_name,' ',c.last_name) AS customer_name,
       SUM(p.amount) AS lifetime_value
FROM customer c
JOIN payment p ON c.customer_id = p.customer_id
GROUP BY c.customer_id
ORDER BY lifetime_value DESC
LIMIT 10;

-- =========================================================
-- Problem 10: Customers with lowest spending
-- Business Use: Target low-value customers with promotions
-- =========================================================
SELECT c.customer_id,
       CONCAT(c.first_name,' ',c.last_name) AS customer_name,
       SUM(p.amount) AS total_spent
FROM customer c
JOIN payment p ON c.customer_id = p.customer_id
GROUP BY c.customer_id
ORDER BY total_spent ASC
LIMIT 10;


-- =========================================================
-- Problem 11: Store-wise revenue comparison
-- Business Use: Compare store performance
-- =========================================================
SELECT s.store_id, SUM(p.amount) AS revenue
FROM store s
JOIN staff st ON s.store_id = st.store_id
JOIN payment p ON st.staff_id = p.staff_id
GROUP BY s.store_id;


-- =========================================================
-- Problem 12: Staff performance based on revenue
-- Business Use: Evaluate employee efficiency
-- =========================================================
SELECT st.staff_id,
       CONCAT(st.first_name,' ',st.last_name) AS staff_name,
       SUM(p.amount) AS revenue
FROM staff st
JOIN payment p ON st.staff_id = p.staff_id
GROUP BY st.staff_id
ORDER BY revenue DESC;

-- =========================================================
-- Problem 13: Inventory count per movie
-- Business Use: Detect overstock or understock
-- =========================================================
SELECT f.title, COUNT(i.inventory_id) AS stock
FROM film f
JOIN inventory i ON f.film_id = i.film_id
GROUP BY f.title;

-- =========================================================
-- Problem 14: Rental frequency vs stock
-- Business Use: Optimize inventory allocation
-- =========================================================
SELECT f.title,
       COUNT(i.inventory_id) AS stock,
       COUNT(r.rental_id) AS rentals
FROM film f
JOIN inventory i ON f.film_id = i.film_id
LEFT JOIN rental r ON i.inventory_id = r.inventory_id
GROUP BY f.title;


-- =========================================================
-- Problem 15: Actor popularity by rentals
-- Business Use: Select actors for future projects
-- =========================================================
SELECT a.first_name, a.last_name, COUNT(r.rental_id) AS rentals
FROM actor a
JOIN film_actor fa ON a.actor_id = fa.actor_id
JOIN film f ON fa.film_id = f.film_id
JOIN inventory i ON f.film_id = i.film_id
JOIN rental r ON i.inventory_id = r.inventory_id
GROUP BY a.actor_id
ORDER BY rentals DESC
LIMIT 10;

-- =========================================================
-- Problem 16: Category-wise average rental rate
-- Business Use: Pricing strategy analysis
-- =========================================================
SELECT c.name AS category,
       AVG(f.rental_rate) AS avg_rate
FROM category c
JOIN film_category fc ON c.category_id = fc.category_id
JOIN film f ON fc.film_id = f.film_id
GROUP BY c.name;

-- =========================================================
-- Problem 17: Movies with highest rental rate but low demand
-- Business Use: Repricing decisions
-- =========================================================
SELECT f.title, f.rental_rate, COUNT(r.rental_id) AS rentals
FROM film f
JOIN inventory i ON f.film_id = i.film_id
LEFT JOIN rental r ON i.inventory_id = r.inventory_id
GROUP BY f.title, f.rental_rate
ORDER BY rentals ASC;

-- =========================================================
-- Problem 18: Customer rental frequency
-- Business Use: Identify loyal customers
-- =========================================================
SELECT c.customer_id,
       COUNT(r.rental_id) AS total_rentals
FROM customer c
JOIN rental r ON c.customer_id = r.customer_id
GROUP BY c.customer_id
ORDER BY total_rentals DESC;

-- =========================================================
-- Problem 19: Inactive customers
-- Business Use: Customer re-engagement campaigns
-- =========================================================
SELECT c.customer_id, c.first_name, c.last_name
FROM customer c
LEFT JOIN rental r ON c.customer_id = r.customer_id
WHERE r.rental_id IS NULL;

-- =========================================================
-- Problem 20: Average revenue per customer
-- Business Use: Measure customer profitability
-- =========================================================
SELECT AVG(total_spent) AS avg_customer_revenue
FROM (
    SELECT customer_id, SUM(amount) AS total_spent
    FROM payment
    GROUP BY customer_id
) t;


-- =========================================================
-- Problem 21: Revenue contribution percentage by category
-- Business Use: Strategic content investment
-- =========================================================
SELECT c.name,
       SUM(p.amount) / (SELECT SUM(amount) FROM payment) * 100 AS revenue_percentage
FROM category c
JOIN film_category fc ON c.category_id = fc.category_id
JOIN film f ON fc.film_id = f.film_id
JOIN inventory i ON f.film_id = i.film_id
JOIN rental r ON i.inventory_id = r.inventory_id
JOIN payment p ON r.rental_id = p.rental_id
GROUP BY c.name;


-- =========================================================
-- Problem 22: Average payment amount
-- Business Use: Understand pricing behavior
-- =========================================================
SELECT AVG(amount) AS avg_payment
FROM payment;


-- =========================================================
-- Problem 23: Peak rental hours
-- Business Use: Optimize system and staff scheduling
-- =========================================================
SELECT HOUR(rental_date) AS hour,
       COUNT(*) AS rentals
FROM rental
GROUP BY hour
ORDER BY rentals DESC;

-- =========================================================
-- Problem 24: Movies never rented
-- Business Use: Content removal decision
-- =========================================================
SELECT f.title
FROM film f
LEFT JOIN inventory i ON f.film_id = i.film_id
LEFT JOIN rental r ON i.inventory_id = r.inventory_id
WHERE r.rental_id IS NULL;

-- =========================================================
-- Problem 25: Revenue ranking by customer (Window Function)
-- Business Use: Customer segmentation
-- =========================================================
SELECT customer_id,
       SUM(amount) AS revenue,
       RANK() OVER (ORDER BY SUM(amount) DESC) AS revenue_rank
FROM payment
GROUP BY customer_id;

